export const POSTGRES_SCHEMA_VERSION = 4;

export const POSTGRES_SCHEMA_SQL = `
CREATE TABLE sessions (
  session_hash TEXT PRIMARY KEY,
  csrf_hash TEXT NOT NULL,
  user_id INTEGER NOT NULL,
  role TEXT NOT NULL,
  email TEXT NOT NULL DEFAULT '',
  username TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  last_seen_at TEXT NOT NULL
);
CREATE INDEX sessions_expires_idx ON sessions(expires_at);

CREATE TABLE synced_users (
  user_id INTEGER PRIMARY KEY,
  email TEXT NOT NULL DEFAULT '',
  username TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT 'user',
  status TEXT NOT NULL DEFAULT '',
  balance_cents TEXT NOT NULL DEFAULT '0',
  total_recharged_cents TEXT NOT NULL DEFAULT '0',
  allowed_groups_json TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL,
  upstream_updated_at TEXT,
  synced_at TEXT NOT NULL
);
CREATE INDEX synced_users_status_idx ON synced_users(status);

CREATE TABLE recharge_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_type TEXT NOT NULL,
  source_id TEXT NOT NULL,
  user_id INTEGER NOT NULL,
  value_cents TEXT NOT NULL,
  used_at TEXT NOT NULL,
  code TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  synced_at TEXT NOT NULL,
  UNIQUE(source_type, source_id)
);
CREATE INDEX recharge_events_user_idx ON recharge_events(user_id);
CREATE INDEX recharge_events_used_idx ON recharge_events(used_at);

CREATE TABLE sync_cursors (
  source TEXT PRIMARY KEY,
  cursor_json TEXT NOT NULL DEFAULT '{}',
  last_started_at TEXT,
  last_completed_at TEXT,
  last_status TEXT NOT NULL DEFAULT 'never',
  last_error TEXT,
  item_count INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE activity_groups (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  action_url TEXT NOT NULL DEFAULT '',
  action_label TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'inactive',
  visibility_rule_json TEXT,
  created_by INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX activity_groups_visible_idx ON activity_groups(status, sort_order, id);

CREATE TABLE activity_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id INTEGER NOT NULL REFERENCES activity_groups(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  action_url TEXT NOT NULL,
  action_label TEXT NOT NULL DEFAULT '',
  enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX activity_items_group_idx ON activity_items(group_id, enabled, sort_order, id);

CREATE TABLE lotteries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'not_started',
  rule_json TEXT NOT NULL,
  published INTEGER NOT NULL DEFAULT 0 CHECK (published IN (0, 1)),
  starts_at TEXT,
  ends_at TEXT,
  auto_draw_at TEXT,
  auto_draw_attempted_at TEXT,
  auto_draw_error TEXT,
  created_by INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  candidates_generated_at TEXT,
  locked_at TEXT,
  drawn_at TEXT
);
CREATE INDEX lotteries_status_idx ON lotteries(status, id);
CREATE INDEX lotteries_auto_draw_idx ON lotteries(status, auto_draw_at, auto_draw_attempted_at, id);

CREATE TABLE prizes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lottery_id INTEGER NOT NULL REFERENCES lotteries(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  winner_count INTEGER NOT NULL,
  reward_type TEXT NOT NULL,
  reward_value TEXT NOT NULL DEFAULT '0',
  group_id INTEGER,
  validity_days INTEGER,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX prizes_lottery_idx ON prizes(lottery_id, sort_order, id);

CREATE TABLE candidate_snapshots (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lottery_id INTEGER NOT NULL REFERENCES lotteries(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL,
  email TEXT NOT NULL DEFAULT '',
  username TEXT NOT NULL DEFAULT '',
  eligible INTEGER NOT NULL CHECK (eligible IN (0, 1)),
  facts_json TEXT NOT NULL,
  explanation_json TEXT NOT NULL,
  generated_at TEXT NOT NULL,
  locked_at TEXT,
  UNIQUE(lottery_id, user_id)
);
CREATE INDEX candidate_snapshots_pool_idx ON candidate_snapshots(lottery_id, eligible, user_id);

CREATE TABLE draw_rounds (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lottery_id INTEGER NOT NULL REFERENCES lotteries(id) ON DELETE RESTRICT,
  idempotency_key TEXT NOT NULL,
  status TEXT NOT NULL,
  candidate_count INTEGER NOT NULL,
  winner_count INTEGER NOT NULL,
  created_by INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  completed_at TEXT,
  UNIQUE(lottery_id, idempotency_key)
);

CREATE TABLE winners (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  draw_round_id INTEGER NOT NULL REFERENCES draw_rounds(id) ON DELETE RESTRICT,
  lottery_id INTEGER NOT NULL REFERENCES lotteries(id) ON DELETE RESTRICT,
  prize_id INTEGER NOT NULL REFERENCES prizes(id) ON DELETE RESTRICT,
  user_id INTEGER NOT NULL,
  reward_status TEXT NOT NULL,
  created_at TEXT NOT NULL,
  UNIQUE(draw_round_id, user_id)
);
CREATE INDEX winners_lottery_idx ON winners(lottery_id, id);

CREATE TABLE outbox_jobs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  winner_id INTEGER NOT NULL UNIQUE REFERENCES winners(id) ON DELETE RESTRICT,
  job_type TEXT NOT NULL,
  status TEXT NOT NULL,
  payload_json TEXT NOT NULL DEFAULT '{}',
  attempts INTEGER NOT NULL DEFAULT 0,
  next_attempt_at TEXT,
  last_error TEXT,
  external_ref TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX outbox_pending_idx ON outbox_jobs(status, next_attempt_at, id);

CREATE TABLE audit_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id INTEGER,
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  details_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL
);
CREATE INDEX audit_events_entity_idx ON audit_events(entity_type, entity_id, id);

CREATE TABLE synced_groups (
  group_id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  platform TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT '',
  is_exclusive INTEGER NOT NULL DEFAULT 0 CHECK (is_exclusive IN (0, 1)),
  rate_multiplier DOUBLE PRECISION NOT NULL DEFAULT 1,
  subscription_type TEXT NOT NULL DEFAULT '',
  upstream_updated_at TEXT,
  synced_at TEXT NOT NULL
);
CREATE INDEX synced_groups_status_idx ON synced_groups(status, name);

CREATE TABLE group_entitlement_rules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id INTEGER NOT NULL UNIQUE,
  name TEXT NOT NULL DEFAULT '',
  enabled INTEGER NOT NULL DEFAULT 0 CHECK (enabled IN (0, 1)),
  revoke_when_ineligible INTEGER NOT NULL DEFAULT 0 CHECK (revoke_when_ineligible IN (0, 1)),
  condition_json TEXT NOT NULL,
  assignment_mode TEXT NOT NULL DEFAULT 'claim' CHECK (assignment_mode = 'claim'),
  activity_description TEXT NOT NULL DEFAULT '',
  activity_starts_at TEXT,
  activity_ends_at TEXT,
  revoke_at TEXT,
  created_by INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  last_executed_at TEXT
);

CREATE TABLE group_entitlement_memberships (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  rule_id INTEGER REFERENCES group_entitlement_rules(id) ON DELETE SET NULL,
  ownership TEXT NOT NULL CHECK (ownership IN ('managed', 'preexisting')),
  status TEXT NOT NULL CHECK (status IN ('active', 'revoked')),
  first_seen_at TEXT NOT NULL,
  granted_at TEXT,
  revoked_at TEXT,
  last_seen_at TEXT NOT NULL,
  last_action TEXT NOT NULL DEFAULT '',
  UNIQUE(group_id, user_id)
);
CREATE INDEX group_memberships_rule_idx ON group_entitlement_memberships(rule_id, status, ownership);
CREATE INDEX group_memberships_user_idx ON group_entitlement_memberships(user_id, status);

CREATE TABLE group_entitlement_runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_id INTEGER REFERENCES group_entitlement_rules(id) ON DELETE SET NULL,
  group_id INTEGER NOT NULL,
  rule_name TEXT NOT NULL DEFAULT '',
  group_name TEXT NOT NULL DEFAULT '',
  mode TEXT NOT NULL CHECK (mode IN ('preview', 'execute', 'revoke', 'expire')),
  status TEXT NOT NULL CHECK (status IN ('running', 'succeeded', 'partial', 'failed')),
  eligible_count INTEGER NOT NULL DEFAULT 0,
  grant_count INTEGER NOT NULL DEFAULT 0,
  revoke_count INTEGER NOT NULL DEFAULT 0,
  managed_count INTEGER NOT NULL DEFAULT 0,
  preexisting_count INTEGER NOT NULL DEFAULT 0,
  unchanged_count INTEGER NOT NULL DEFAULT 0,
  error_count INTEGER NOT NULL DEFAULT 0,
  result_json TEXT NOT NULL DEFAULT '{}',
  actor_user_id INTEGER,
  started_at TEXT NOT NULL,
  completed_at TEXT
);
CREATE INDEX group_runs_rule_idx ON group_entitlement_runs(rule_id, id DESC);

CREATE TABLE checkin_campaigns (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  published INTEGER NOT NULL DEFAULT 0 CHECK (published IN (0, 1)),
  condition_json TEXT NOT NULL,
  reward_type TEXT NOT NULL DEFAULT 'none' CHECK (reward_type IN ('none', 'balance')),
  reward_value TEXT NOT NULL DEFAULT '0',
  starts_at TEXT,
  ends_at TEXT,
  created_by INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX checkin_campaigns_visible_idx ON checkin_campaigns(published, starts_at, ends_at, id);

CREATE TABLE checkin_records (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id INTEGER NOT NULL REFERENCES checkin_campaigns(id) ON DELETE RESTRICT,
  user_id INTEGER NOT NULL,
  local_date TEXT NOT NULL,
  streak_days INTEGER NOT NULL DEFAULT 1,
  facts_json TEXT NOT NULL DEFAULT '{}',
  reward_status TEXT NOT NULL DEFAULT 'none' CHECK (reward_status IN ('none', 'pending', 'succeeded', 'failed')),
  reward_external_ref TEXT,
  reward_error TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(campaign_id, user_id, local_date)
);
CREATE INDEX checkin_records_user_idx ON checkin_records(user_id, campaign_id, local_date DESC);

CREATE TABLE lottery_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lottery_id INTEGER NOT NULL REFERENCES lotteries(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL,
  facts_json TEXT NOT NULL,
  explanation_json TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(lottery_id, user_id)
);
CREATE INDEX lottery_entries_lottery_idx ON lottery_entries(lottery_id, user_id);

CREATE TABLE api_request_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id TEXT NOT NULL,
  aggregation_key TEXT UNIQUE,
  created_at TEXT NOT NULL,
  last_seen_at TEXT NOT NULL,
  request_count INTEGER NOT NULL DEFAULT 1,
  duration_ms INTEGER NOT NULL DEFAULT 0,
  ip_address TEXT NOT NULL DEFAULT '',
  user_id INTEGER,
  role TEXT NOT NULL DEFAULT '',
  method TEXT NOT NULL,
  path TEXT NOT NULL,
  route_pattern TEXT NOT NULL DEFAULT '',
  status_code INTEGER NOT NULL,
  result_code TEXT NOT NULL DEFAULT '',
  rate_limit_scope TEXT NOT NULL DEFAULT '',
  user_agent TEXT NOT NULL DEFAULT ''
);
CREATE INDEX api_request_logs_created_idx ON api_request_logs(created_at DESC, id DESC);
CREATE INDEX api_request_logs_ip_idx ON api_request_logs(ip_address, id DESC);
CREATE INDEX api_request_logs_user_idx ON api_request_logs(user_id, id DESC);
CREATE INDEX api_request_logs_status_idx ON api_request_logs(status_code, id DESC);
`;

export const POSTGRES_SCHEMA_MIGRATIONS = Object.freeze({
  2: `
    CREATE TABLE IF NOT EXISTS api_request_logs (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      request_id TEXT NOT NULL,
      aggregation_key TEXT UNIQUE,
      created_at TEXT NOT NULL,
      last_seen_at TEXT NOT NULL,
      request_count INTEGER NOT NULL DEFAULT 1,
      duration_ms INTEGER NOT NULL DEFAULT 0,
      ip_address TEXT NOT NULL DEFAULT '',
      user_id INTEGER,
      role TEXT NOT NULL DEFAULT '',
      method TEXT NOT NULL,
      path TEXT NOT NULL,
      route_pattern TEXT NOT NULL DEFAULT '',
      status_code INTEGER NOT NULL,
      result_code TEXT NOT NULL DEFAULT '',
      rate_limit_scope TEXT NOT NULL DEFAULT '',
      user_agent TEXT NOT NULL DEFAULT ''
    );
    CREATE INDEX IF NOT EXISTS api_request_logs_created_idx ON api_request_logs(created_at DESC, id DESC);
    CREATE INDEX IF NOT EXISTS api_request_logs_ip_idx ON api_request_logs(ip_address, id DESC);
    CREATE INDEX IF NOT EXISTS api_request_logs_user_idx ON api_request_logs(user_id, id DESC);
    CREATE INDEX IF NOT EXISTS api_request_logs_status_idx ON api_request_logs(status_code, id DESC);
  `,
  3: `
    ALTER TABLE group_entitlement_runs
      DROP CONSTRAINT IF EXISTS group_entitlement_runs_mode_check;
    ALTER TABLE group_entitlement_runs
      ADD CONSTRAINT group_entitlement_runs_mode_check
      CHECK (mode IN ('preview', 'execute', 'revoke', 'expire'));
  `,
  4: `
    ALTER TABLE group_entitlement_rules ADD COLUMN IF NOT EXISTS revoke_at TEXT;
  `
});
